import type { Metadata } from "next";
import "./globals.css";

import { Exo } from "next/font/google";
import SideNav from "./ui/components/sidenav";

export const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${exo.className} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <div className="grow flex-col justify-start items-start gap-2.5 inline-flex">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
