import type { Metadata } from "next";
import "./globals.css";

import { Exo } from "next/font/google";

export const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${exo.className} antialiased`}>{children}</body>
    </html>
  );
}
