services:
  traefik:
    image: traefik:v3.6
    container_name: hurribrain-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - axon
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: hurribrain
      POSTGRES_USER: neuron
      POSTGRES_PASSWORD: synapse
    networks:
      - axon
    # ports:
    #   - "5432:5432"
    container_name: hurribrain-postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    networks:
      - axon
    # ports:
    #   - "6379:6379"
    container_name: hurribrain-redis
    restart: unless-stopped

  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    networks:
      - axon
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      POSTGRES_HOST: "hurribrain-postgres"
      POSTGRES_PORT: 5432
      REDIS_HOST: "hurribrain-redis"
      REDIS_PORT: 6379
    depends_on:
      - database
      - redis
    container_name: hurribrain-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

  web:
    build:
      context: ./
      dockerfile: ./apps/app/Dockerfile
    networks:
      - axon
    ports:
      - "8081:8081"
    environment:
      API_HOST: "hurribrain-api"
    container_name: hurribrain-web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"

volumes:
  pg_data:
    
networks:
  axon:
    driver: bridge
