services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: hurribrain
      POSTGRES_USER: neuron
      POSTGRES_PASSWORD: synapse
    networks:
      - axon
    container_name: hurribrain-postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    networks:
      - axon
    container_name: hurribrain-redis
    restart: unless-stopped

  api:
    # build:
    #   context: ./
    #   dockerfile: ./apps/api/Dockerfile
    networks:
      - axon
    ports:
      - "3002:3002"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    environment:
      POSTGRES_HOST: "hurribrain-postgres"
      REDIS_HOST: "hurribrain-redis"
      PORT: 3002
      HOST: "0.0.0.0"
    container_name: hurribrain-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`)"
    image: "ghcr.io/angelzatch/hurribrain-api:latest"

  web:
    # build:
    #   context: ./
    #   dockerfile: ./apps/app/Dockerfile
    #   args:
    #     API_URL: "http://api.docker.localhost"
    networks:
      - axon
    container_name: hurribrain-web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.docker.localhost`)"
    image: "ghcr.io/angelzatch/hurribrain-web:latest"

  traefik:
    image: traefik:v3.6
    container_name: hurribrain-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - axon
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro

volumes:
  pg_data:
    
networks:
  axon:
    driver: bridge
