log:
  level: DEBUG
api:
  dashboard: true
  insecure: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: axon
certificatesResolvers:
  le:
   acme:
    email: angelzatch@gmail.com
    storage: /letsencrypt/acme.json
    dnsChallenge:
      provider: digitalocean
      resolvers:
        - "ns1.digitalocean.com"
        - "ns2.digitalocean.com"
        - "ns3.digitalocean.com"
      propagation:
        delayBeforeChecks: 60