name: Deploy

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Build and Push
        env:
          BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          echo "$BUILD_TOKEN" | docker login ghcr.io --username AngelZatch --password-stdin
          docker compose --file docker-compose.prod.yml build --no-cache api web
          docker push ghrc.io/angelzatch/hurribrain-api:latest
          docker push ghrc.io/angelzatch/hurribrain-web:latest