name: Deploy

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  docker:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Web
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./apps/app/Dockerfile
          push: true
          tags: ghcr.io/angelzatch/hurribrain-web:latest
          labels: "org.opencontainers.image.source https://github.com/angelzatch/hurribrain"
      

      - name: Build and Push API
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./apps/api/Dockerfile
          push: true
          tags: ghcr.io/angelzatch/hurribrain-api:latest
          labels: "org.opencontainers.image.source https://github.com/angelzatch/hurribrain"
  
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5      
      - name: Refresh Compose File
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEV_DROPLET_HOST }}
          username: ${{ secrets.DEV_DROPLET_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "docker-compose.prod.yml, config/traefik.prod.yaml"
          target: ~/
      - name: Run Compose
        uses: appleboy/ssh-action@v1
        env:
          USERNAME: ${{ github.actor }}
          APPTOKEN: ${{ secrets.PULL_TOKEN }}
          CERTTOKEN: ${{ secrets.CERT_TOKEN }}
        with:
          host: ${{ secrets.DEV_DROPLET_HOST }}
          username: ${{ secrets.DEV_DROPLET_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          envs: USERNAME,APPTOKEN,CERTTOKEN
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            rm .env
            echo "DO_AUTH_TOKEN:'$CERTTOKEN'" >> ~/.env 
            docker compose -f ~/docker-compose.prod.yml pull && docker compose -f ~/docker-compose.prod.yml up -d